# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 212f438207e06ecfcdbda4b970c286abd912830316d054cfde01f28fe998516a2e0676d9105bd361d0444ccbffcf47962f6b13cbc6060bfe952c5eeb9adeb7be

test:
  secret_key_base: 15dfb435cfcfd572be256a79e2695a2c484be3dda347d12cc2425f0cb8df8b09a025862321565f22fd76209fbf6c7df60cbd16b1652f50fb8f6fe2b4362ff74b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
